version: '3.9'
services:
  redis:
    restart: always
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - tas
  mysql:
    restart: always
    image: mysql
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
networks:
  tas:
